### ISSUE TITLE
New (Unknown) Guard pressure measurements 

### ISSUE THREAD

**Issue by daxyorg** [Flo-Schilli/homeassistant-grohe_sense#24]
Today I saw some new (unknown) measurements for Grohe Guard. 
I think they will have values only if there is a leakage.
Below the screen you can find the debug log.
Feel free to asked me for tests, also leakage test ;)
I'm with v0.9.8.

**Update: Now I see you wrote about those measurements in the description. I will test a flood to see if there will be parameters. I will also stop the water before the Grohe for a few minutes to see if there will be any changes.**

<img width="280" alt="Screenshot 2024-10-13 at 17 26 46" src="https://github.com/user-attachments/assets/1643ab26-656c-447d-aebd-dc03fc58cc47">

2024-10-13 16:14:25.466 DEBUG (MainThread) [custom_components.grohe_sense.sensor] Attaching sensor SensorTypes.LPM_STATUS to device <custom_components.grohe_sense.dto.grohe_device.GroheDevice object at 0xXXXXXXXXX>
2024-10-13 16:14:25.466 DEBUG (MainThread) [custom_components.grohe_sense.sensor] Attaching sensor SensorTypes.LPM_START_TIME to device <custom_components.grohe_sense.dto.grohe_device.GroheDevice object at 0xXXXXXXXXX>
2024-10-13 16:14:25.466 DEBUG (MainThread) [custom_components.grohe_sense.sensor] Attaching sensor SensorTypes.LPM_ESTIMATED_STOP_TIME to device <custom_components.grohe_sense.dto.grohe_device.GroheDevice object at 0xXXXXXXXXX>
2024-10-13 16:14:25.466 DEBUG (MainThread) [custom_components.grohe_sense.sensor] Attaching sensor SensorTypes.LPM_LEAKAGE to device <custom_components.grohe_sense.dto.grohe_device.GroheDevice object at 0xXXXXXXXXX>
2024-10-13 16:14:25.466 DEBUG (MainThread) [custom_components.grohe_sense.sensor] Attaching sensor SensorTypes.LPM_LEAKAGE_LEVEL to device <custom_components.grohe_sense.dto.grohe_device.GroheDevice object at 0xXXXXXXXXX>
2024-10-13 16:14:25.466 DEBUG (MainThread) [custom_components.grohe_sense.sensor] Attaching sensor SensorTypes.LPM_PRESSURE_DROP to device <custom_components.grohe_sense.dto.grohe_device.GroheDevice object at 0xXXXXXXXXX>
2024-10-13 16:14:25.466 DEBUG (MainThread) [custom_components.grohe_sense.sensor] Attaching sensor SensorTypes.LPM_DURATION to device <custom_components.grohe_sense.dto.grohe_device.GroheDevice object at 0xXXXXXXXXX>

**Comment by Flo-Schilli** [comment]
Hi @daxyorg 👋 

it would be great If you could test it with clicking on the "pressure measurement" button.
As my Sense Guard is always doing these measurements in the night - and Grohe not showing any details within their app - I just implemented them here to possibly see why I'm getting sometimes some errors with leaking pipes in the night. 
In general the integration will always take the last pressure measurement and I guess I'll add some more functionality - that if it's running and so on - until there will be a success message, it's taking the last success measurement. 
As said, for me the Sense Guard is making these measurements at least once in the night.
I'm also going to make them more responsive as they are now by refactoring a few components.

So your feedback is definitely appreciated 😊

**Comment by daxyorg** [comment]
First of all, I will test with the develop version 0.9.9.
I also sometimes get a low pressure message at night.

I will keep you updated with a log and info on what I observe.

**Comment by Flo-Schilli** [comment]
Okay that sounds great when you test with 0.9.9 👍 
Are you getting any errors/warnings when clicking on the pressure measurement? In general within the next 5mins you should see updates to the new sensors.

**Comment by daxyorg** [comment]
Now I'm with 0.9.9, after press on the "pressure measurement" button there are no changes, but here it is the log:

<img width="1061" alt="Screenshot 2024-10-13 at 19 26 00" src="https://github.com/user-attachments/assets/4ffc26be-909f-490a-bbe8-c45d0b3d359e">

<img width="659" alt="Screenshot 2024-10-13 at 19 25 00" src="https://github.com/user-attachments/assets/ed6d457e-1e0e-42b7-89f4-cf4ab5d1e4ae">


2024-10-13 19:17:49.280 DEBUG (MainThread) [custom_components.grohe_sense.entities.grohe_blue_update_coordinator] Got the following details for Grohe Blue appliance XXXXXXX: Appliance(id='XXXXXXXX', installation_date='2024-09-11T12:08:50.000+03:00', name='My GROHE Blue Home', serial_number='XXXXXXX', type=104, version='01.04.Z10.0300.0104', tdt='2024-10-13T18:28:08.000+03:00', timezone=180, config=Config(thresholds=None, measurement_period=None, action_on_major_leakage=None, action_on_minor_leakage=None, action_on_micro_leakage=None, monitor_frost_alert=None, monitor_lower_flow_limit=None, monitor_upper_flow_limit=None, monitor_lower_pressure_limit=None, monitor_upper_pressure_limit=None, monitor_lower_temperature_limit=None, monitor_upper_temperature_limit=None, monitor_major_leakage=None, monitor_minor_leakage=None, monitor_micro_leakage=None, monitor_system_error=None, monitor_btw_0_1_and_0_8_leakage=None, monitor_withdrawel_amount_limit_breach=None, detection_interval=None, impulse_ignore=None, time_ignore=None, pressure_tolerance_band=None, pressure_drop=None, detection_time=None, action_on_btw_0_1_and_0_8_leakage=None, action_on_withdrawel_amount_limit_breach=None, withdrawel_amount_limit=None, sprinkler_mode_active_monday=None, sprinkler_mode_active_tuesday=None, sprinkler_mode_active_wednesday=None, sprinkler_mode_active_thursday=None, sprinkler_mode_active_friday=None, sprinkler_mode_active_saturday=None, sprinkler_mode_active_sunday=None, sprinkler_mode_start_time=None, sprinkler_mode_stop_time=None, measurement_transmission_intervall=None, measurement_transmission_intervall_offset=None, co2_type=1, hose_length=90, co2_consumption_medium=48, co2_consumption_carbonated=65, guest_mode_active=False, auto_flush_active=False, flush_confirmed=False, f_parameter=9, l_parameter=1, flow_rate_still=20, flow_rate_medium=25, flow_rate_carbonated=20), role='owner', registration_complete=True, presharedkey='XXXXXXXXXXXXXXX', params=Params(water_hardness=0, carbon_hardness=6, filter_type=1, variant=4, auto_flush_reminder_notif=False, consumables_low_notif=True, product_information_notif=True), error=Errors(errors_1=False, errors_2=False, errors_3=False, errors_4=False, errors_5=False, errors_6=False, errors_7=False, errors_8=False, errors_9=False, errors_10=False, errors_11=False, errors_12=False, errors_13=False, errors_14=False, errors_15=False, errors_16=False, error1_counter=1, error2_counter=1, error3_counter=4, error4_counter=0, error5_counter=0, error6_counter=0, error7_counter=0, error8_counter=0, error9_counter=0, error10_counter=0, error11_counter=0, error12_counter=30, error13_counter=0, error14_counter=0, error15_counter=0, error16_counter=0), state=State(start_time=1728836268, APPLIANCE_SUCCESSFUL_CONFIGURED=False, co2_empty=False, co2_20l_reached=False, filter_empty=False, filter_20l_reached=False, cleaning_mode_active=False, cleaning_needed=False, flush_confirmation_required=False, System_error_bitfield=0), calculate_average_since=None, pressure_notification=None, snooze_status=None, last_pressure_measurement=None, installer=None, command=None, notifications=[], status=[Status(type='update_available', value=0), Status(type='connection', value=1)], data_latest=DataLatest(measurement=MeasurementDto(timestamp='2024-10-13T18:28:08.000+03:00', temperature=None, humidity=None, flow_rate=None, pressure=None, temperature_guard=None, battery=None, cleaning_count=0, date_of_cleaning='2023-10-21T14:26:30.000+03:00', date_of_co2_replacement='2024-10-13T18:28:08.000+03:00', date_of_filter_replacement='2024-10-13T18:28:08.000+03:00', filter_change_count=9, max_idle_time=19814, open_close_cycles_carbonated=682, open_close_cycles_still=2247, operating_time=7653, power_cut_count=81, pump_count=2425, pump_running_time=228, remaining_co2=57, remaining_filter=82, time_since_last_withdrawal=48, time_since_restart=536887329, time_offset=180, water_running_time_carbonated=56, water_running_time_medium=12, water_running_time_still=180, remaining_filter_liters=1645, remaining_co2_liters=32), average_measurements=None))
2024-10-13 19:17:49.284 DEBUG (MainThread) [custom_components.grohe_sense.entities.grohe_blue_update_coordinator] Finished fetching Grohe Blue data in 0.775 seconds (success: True)

**Comment by Flo-Schilli** [comment]
Thanks for the log. It seems like this is only the one for your Grohe Blue. There should be a second request like this from the "grohe_sense_update_coordinator" in the log. Can you please send me this as well.

**Comment by daxyorg** [comment]
2024-10-13 19:10:51.380 DEBUG (MainThread) [custom_components.grohe_sense.entities.grohe_sense_update_coordinator] Finished fetching Grohe Sense data in 1.946 seconds (success: True)

....

2024-10-13 19:17:45.392 DEBUG (MainThread) [custom_components.grohe_sense.entities.grohe_sense_update_coordinator] Finished fetching Grohe Sense data in 2.263 seconds (success: True)
2024-10-13 19:17:46.077 DEBUG (MainThread) [custom_components.grohe_sense.entities.grohe_sense_update_coordinator] Finished fetching Grohe Sense data in 1.824 seconds (success: True)

**Comment by Flo-Schilli** [comment]
Oh I see there is no detailed debug logging for that. I'll add it in develop and will let you know when it is ready.

**Comment by Flo-Schilli** [comment]
So, I added a little bit more logging. You should be able to search for the following log-entry `PRESSURE MEASUREMENT -> `.

**Comment by daxyorg** [comment]
> So, I added a little bit more logging. You should be able to search for the following log-entry `PRESSURE MEASUREMENT -> `.

In v 0.9.10 only this I see:

2024-10-13 19:12:57.882 INFO (MainThread) [custom_components.grohe_sense.entities.grohe_sense_guard_button] Starting pressure measurement for MY GUARD
2024-10-13 19:12:57.882 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Start pressure measurement for appliance XXXXXXXXXXXX
2024-10-13 19:13:44.189 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Get appliance command for appliance XXXXXXXXXXXX
2024-10-13 19:13:44.404 DEBUG (MainThread) [custom_components.grohe_sense.entities.grohe_sense_guard_valve] Valve_open state: True for appliance XXXXXXXXXXXX

**Comment by Flo-Schilli** [comment]
I just added even more logging output, so that it looks like this on my side:

```
Updating GroheTypes.GROHE_SENSE_GUARD (appliance = XXXXXXXX) data
Get appliance data for appliance XXXXXXXX with (from: 2024-10-13 19:58:25.143032+02:00, to: None, group_by: None
Get appliance data for appliance XXXXXXXX with (from: 2024-10-13 18:58:25.143032+02:00, to: None, group_by: OndusGroupByTypes.HOUR
Get appliance notifications for appliance XXXXXXXX
Get last pressure measurement for appliance XXXXXXXX
Get appliance details for appliance XXXXXXXX
PRESSURE MEASUREMENT -> Received the following pressure measurement for applianceXXXXXXXX: LastPressureMeasurement(id='XXXXXXXX', status='SUCCESS', estimated_stop_time='2024-10-13T17:25:26.000+02:00', start_time='2024-10-13T17:10:26.000+02:00', error_message='SUCCESS', leakage=False, leakage_level=0, duration=898, pressure_drop=-0.3, max_flow_rate=None)
Finished fetching Grohe Sense data in 2.591 seconds (success: True)
```

**Comment by daxyorg** [comment]
v0.9.11:

2024-10-13 21:04:54.963 DEBUG (MainThread) [custom_components.grohe_sense.entities.grohe_sense_update_coordinator] PRESSURE MEASUREMENT -> Did a pressure measurement for appliance xxxxxxxx but only received the following data: Appliance(id='xxxxxxxx', installation_date='2022-12-24T15:57:38.000+02:00', name='MY GUARD', serial_number='xxxxxxx', type=103, version='01.44.Z22.0400.0101', tdt='2024-10-13T21:03:32.000+03:00', timezone=120, config=Config(thresholds=[Threshold(type='min', value=3, enabled=False, quantity='flowrate'), Threshold(type='max', value=50, enabled=True, quantity='flowrate'), Threshold(type='min', value=2, enabled=False, quantity='pressure'), Threshold(type='max', value=8, enabled=False, quantity='pressure'), Threshold(type='min', value=5, enabled=False, quantity='temperature_guard'), Threshold(type='max', value=45, enabled=False, quantity='temperature_guard')], measurement_period=900, action_on_major_leakage=1, action_on_minor_leakage=1, action_on_micro_leakage=0, monitor_frost_alert=True, monitor_lower_flow_limit=False, monitor_upper_flow_limit=True, monitor_lower_pressure_limit=False, monitor_upper_pressure_limit=False, monitor_lower_temperature_limit=False, monitor_upper_temperature_limit=False, monitor_major_leakage=True, monitor_minor_leakage=True, monitor_micro_leakage=True, monitor_system_error=False, monitor_btw_0_1_and_0_8_leakage=True, monitor_withdrawel_amount_limit_breach=True, detection_interval=11250, impulse_ignore=10, time_ignore=20, pressure_tolerance_band=10, pressure_drop=50, detection_time=30, action_on_btw_0_1_and_0_8_leakage=1, action_on_withdrawel_amount_limit_breach=1, withdrawel_amount_limit=300, sprinkler_mode_active_monday=True, sprinkler_mode_active_tuesday=True, sprinkler_mode_active_wednesday=True, sprinkler_mode_active_thursday=True, sprinkler_mode_active_friday=True, sprinkler_mode_active_saturday=True, sprinkler_mode_active_sunday=True, sprinkler_mode_start_time=488, sprinkler_mode_stop_time=503, measurement_transmission_intervall=900, measurement_transmission_intervall_offset=1, co2_type=None, hose_length=None, co2_consumption_medium=None, co2_consumption_carbonated=None, guest_mode_active=None, auto_flush_active=None, flush_confirmed=None, f_parameter=None, l_parameter=None, flow_rate_still=None, flow_rate_medium=None, flow_rate_carbonated=None), role='owner', registration_complete=True, presharedkey=None, params=None, error=None, state=None, calculate_average_since='2022-12-24T13:57:38.000Z', pressure_notification=True, snooze_status='NON_EXISTENT', last_pressure_measurement=None, installer=Installer(name='', email='', phone=''), command=Command(temp_user_unlock_on=False, reason_for_change=0, pressure_measurement_running=False, buzzer_on=False, buzzer_sound_profile=2, valve_open=True, measure_now=False), notifications=[], status=[Status(type='update_available', value=0), Status(type='connection', value=1), Status(type='wifi_quality', value=-1)], data_latest=DataLatest(measurement=MeasurementDto(timestamp='2024-10-13T20:53:54.000+03:00', temperature=None, humidity=None, flow_rate=None, pressure=3.5, temperature_guard=24.0, battery=None, cleaning_count=None, date_of_cleaning=None, date_of_co2_replacement=None, date_of_filter_replacement=None, filter_change_count=None, max_idle_time=None, open_close_cycles_carbonated=None, open_close_cycles_still=None, operating_time=None, power_cut_count=None, pump_count=None, pump_running_time=None, remaining_co2=None, remaining_filter=None, time_since_last_withdrawal=None, time_since_restart=None, time_offset=None, water_running_time_carbonated=None, water_running_time_medium=None, water_running_time_still=None, remaining_filter_liters=None, remaining_co2_liters=None), average_measurements=None))

**Comment by Flo-Schilli** [comment]
Okay, it seems like your Sense Guard is not receiving any 'pressure measurement'. Can you try to start it from within the Grohe Sense App and check what's happening there.
I do get a bunch of historic measurements as well.

**Comment by daxyorg** [comment]
I'm not sure, but I think that I have a 'pressure measurement'. Maybe I cannot find the correct log.
Last pressure update before 43 sec.

<img width="380" alt="Screenshot 2023-10-12 at 19 07 25" src="https://github.com/user-attachments/assets/5c0f2070-eadb-415d-8675-ab6ef751dc03">

<img width="380" alt="Screenshot 2023-10-12 at 19 07 25" src="https://github.com/user-attachments/assets/57fe55c6-54f0-4029-9320-c9b148aaa572">

**Comment by Flo-Schilli** [comment]
Can you please check if you do have an update available. As I can see in the versions mine does have a more actual version:

![image](https://github.com/user-attachments/assets/6705409d-738b-4724-b5a1-afecdc80be35)

And within the Grohe Sense App I can start a pressure measurement manually as well (like how you should be able to do it now from within HomeAssistant)

**Comment by daxyorg** [comment]
Oh, I see. May be the Guard version is too old, but on my iPhone there is no updates on the app.
So, now I will install the app on Android and will give you more info in a few minutes.

<img width="348" alt="Screenshot 2024-10-13 at 21 45 38" src="https://github.com/user-attachments/assets/d6a70026-ea4c-44b8-912a-05c56d73ab23">

**Comment by Flo-Schilli** [comment]
I'll add - maybe later or latest tomorrow - an update_available status sensor to Home Assistant as Grohe does provide that information in one of the payloads.
I'll ping you once it is integrated.

**Comment by daxyorg** [comment]
I installed the app on Android, but don't receive any firm updates :/
I try with and without check in Settings -> Automatic Device Updates.
I'm curios what is the lates firm version of your sense sensors? Thanks in advance for the info.

I will contact the Grohe how to update my firms.

**Comment by Flo-Schilli** [comment]
Okay that's really strange that there is no firmware update available for you. I'm not sure if it has maybe something to do with different hardware revisions? But that's really just a wild guess.
Once on my PC, I'll check for the installation date of mine as I do not find it in the Grohe App right now, but I should see it very fast within the payload 😊

Also here is a screenshot of my android app with the 'pipe check' button. App version is 2.1.0-release (build 20059).

![Screenshot_20241013-211611~2.png](https://github.com/user-attachments/assets/e1faf6ed-161a-4c8d-a892-e91842b8c6ea)

The version of my Sense sensor is: 01.20.Z20.0400.0100

**Comment by daxyorg** [comment]
First of all really thanks for your support and this conversation.
May be you are right about hardware version.
My hardware ver. is IS ID: 22013-.....
I hade only one firm update, when I installed the Guard, before an year.

Here it is the version of my apps, I think there are up-to-date.

Android:
<img width="280" alt="Screenshot 2023-10-12 at 19 07 25" src="https://github.com/user-attachments/assets/45062c9b-0476-41ed-a1fd-09e7ea2509b9">

iPhone:
<img width="280" alt="Screenshot 2023-10-12 at 19 07 25" src="https://github.com/user-attachments/assets/060b950a-0f28-4f74-b393-d284299525dc">

Sensors:
<img width="322" alt="Screenshot 2024-10-13 at 22 28 37" src="https://github.com/user-attachments/assets/309e0341-1c11-4348-ab37-d3f8b075d00c">

**Comment by Flo-Schilli** [comment]
Thank you too and you're welcome. Without you I wouldn't know that there are firmware version specific features enabled/disabled in the devices. So thanks for that.

I do have the same IC ID, so also starting with 22013. Unfortunately I also didn't found any information about how to read those hardware versions.
Also unfortunately while changing the Wifi here, I had to rejoin the device, so I do not see when I first installed them. Need to check where I bought it :)

For the Sensors we do have the same versions installed and the Apps also look like the newest. So why is your Sense Guard not getting the update and also not getting it shown.
Nevertheless I'll integrate the status sensor within HomeAssistant really soon, so we also can see it there :)

**Comment by daxyorg** [comment]
Tomorrow I'll try to connect it to different router with other operator ;)
Thank you so much for all you do!

**Comment by Flo-Schilli** [comment]
@daxyorg I've just disabled the pressure measurement for any software version less than 3.6 in develop. Can you confirm that it is disabled on your side now?

**Comment by Flo-Schilli** [comment]
How are your tests going with the different routers and have you already got feedback from Grohe why yours is still on a different software version?

**Comment by daxyorg** [comment]
> How are your tests going with the different routers and have you already got feedback from Grohe why yours is still on a different software version?

Hi, sorry for the delay. Now I'm trying to connect and will provide more info about an hour.

**Comment by daxyorg** [comment]
> How are your tests going with the different routers and have you already got feedback from Grohe why yours is still on a different software version?

Hi! I tried with 2 different routers and 2 different wired and wireless operators, but I haven't received any updates.
So, may be you are right - there are different hardware.

**Comment by Flo-Schilli** [comment]
Oh no, thats not good that you didn't received any updates :( 
Maybe it is really the HW-Version or some country specific settings as well but unfortunatelly I really don't know :(
As far as I can see there is also no Hardware - Version information within the payload, so Grohe then will identify updates on serial number of the device in the backend.
Within the newest version you should not see the button and the lpm - sensors, right? 
I'll dig a little bit more into that and check if I can find out something in general towards this :)

**Comment by daxyorg** [comment]
Yes, maybe I'll downgrade to v 0.9.11, because of these errors:

2024-10-15 16:30:44.063 ERROR (MainThread) [custom_components.grohe_sense.api.ondus_api] Could not access url /oidc/login ondus://idp2-apigw.cloud.grohe.com/v3/iot/oidc/token?state=XXXXXXXXXX
2024-10-15 16:30:44.064 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Grohe Sense for grohe_sense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/grohe_sense/__init__.py", line 21, in async_setup_entry
    state = await api.login(entry.data[CONF_USERNAME], entry.data[CONF_PASSWORD])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/grohe_sense/api/ondus_api.py", line 287, in login
    cookie, action = await self.__get_oidc_action()
    ^^^^^^^^^^^^^^
