### ISSUE TITLE
Cannot configure

### ISSUE THREAD

**Issue by pMRaptor** [Flo-Schilli/homeassistant-grohe_sense#28]
Logg looks like this. Not sure what is wrong.

Logger: homeassistant.config_entries
Kilde: config_entries.py:604
Førs oppstått: 17:14:45 (1 hendelser)
Sist logget: 17:14:45

Error setting up entry Grohe Sense for grohe_sense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/grohe_sense/__init__.py", line 21, in async_setup_entry
    state = await api.login(entry.data[CONF_USERNAME], entry.data[CONF_PASSWORD])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/grohe_sense/api/ondus_api.py", line 287, in login
    cookie, action = await self.__get_oidc_action()
    ^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

**Comment by Flo-Schilli** [comment]
Hi @pMRaptor 👋

can you confirm that the entered username and password is correct.
Also, have you already enabled the debug logging for the integration? Because there should be a little more info then within the logs.
I'll check within the next couple of days what other problems could lead to the problem that you're not able to obtain the token.

**Comment by pMRaptor** [comment]
Hi Flo.
I have dobbel checked my password and it is working in Node-red config. 
Updated file with debug setup:

2024-10-21 20:47:26.118 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration grohe_sense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-21 20:47:51.274 DEBUG (MainThread) [custom_components.grohe_sense] Loading Grohe Sense
2024-10-21 20:47:51.275 INFO (MainThread) [custom_components.grohe_sense.api.ondus_api] Login to Ondus API
2024-10-21 20:47:51.275 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Login with username/password
2024-10-21 20:47:54.248 DEBUG (MainThread) [custom_components.grohe_sense.dto.grohe_device] Getting all available Grohe devices
2024-10-21 20:47:54.248 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Get locations
2024-10-21 20:47:54.380 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Get rooms for location 4641028
2024-10-21 20:47:54.476 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Get appliances for location 4641028 and room 4073026
2024-10-21 20:47:54.885 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Grohe Sense for grohe_sense
File "/config/custom_components/grohe_sense/__init__.py", line 23, in async_setup_entry
devices: List[GroheDevice] = await GroheDevice.get_devices(api)
File "/config/custom_components/grohe_sense/dto/grohe_device.py", line 81, in get_devices
File "/config/custom_components/grohe_sense/api/ondus_api.py", line 362, in get_appliances

**Comment by Flo-Schilli** [comment]
I see, now he is also definitely logged in and also getting the room and location back. But when the appliance should be returned there is something wrong. I'll add some more debug logging tomorrow.
What devices are you owning? Seems like at least one Grohe Sense, is that right?

**Comment by Flo-Schilli** [comment]
I do have an idea what it could be.
Once updated, there will be more debug output and I'll ping you so that you can try again.

**Comment by pMRaptor** [comment]
Hi. 
I own one Grohe Protect and 2 Sense. I also have one extra Sense that is offline. 

Thanks for quick reply.

**Comment by Flo-Schilli** [comment]
Hi,

I just updated the version with more debug information and that it should not fail if there is a type returned which is not know to the integration yet (your Grohe Protect).
It should now output a warning with more information about the failed device, but you should be able to setup the rest of your devices.
Would be great if you could send  me the warning information so that I can try to integrate the Grohe Protect.

**Comment by pMRaptor** [comment]
Thanks for the quick update. All devices integrated perfect this time. No Warning :)
I have searched all over to get this integrated and now it works. Thanks for this.
