### ISSUE TITLE
testing/pressure_measurement impression

### ISSUE THREAD

**Issue by daxyorg** [Flo-Schilli/homeassistant-grohe_sense#33]
Hi,

First of all thanks for your patience and waiting.
So, what I did and what's happen:

1). Here it is the version which I received from Grohe -` 02.05 `(not 2.5):
<img width="400" alt="Screenshot" src="https://github.com/user-attachments/assets/58d0428f-bdfa-4943-ae86-85cf37d52198">

2). I replaced all files in HA folder `grohe_sense` with these from the repo `testing/pressure_measurement`
When I restart a HA, received "Failed to set up" with this error message:

2024-11-24 22:22:35.882 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Grohe Sense for grohe_sense
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/grohe_sense/_init__-py", Line 23, in async_setup_entry
devices: List[GroheDevice] = await GroheDevice.get_devices(api)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/grohe_sense/dto/grohe_device.py"
, line 81, in get_devices
appliances = await ondus_api.get_appliances(location.id, room.id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/grohe_sense/api/ondus_api.py", line 362, in get_appliances return [Appliance.from_dictappliance) for appliance in data]

File "/usr/local/lib/python3.12/site-packages/dataclasses_json/api.py"
return_decode_dataclass(cls, kvs, infer_missing)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
, line 70, in from_dict
File "/usr/local/lib/python3.12/site-packages/dataclasses_json/core.py", line 185, in _decode_dataclass-
field_value = kvs[field.name]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

KeyError: 'config'

**Comment by Flo-Schilli** [comment]
Okay, I was faster :smile: 

I just pushed everything from DEV into this branch. Can you please try again. It's working on my side on an empty HA.
If the error is still coming, there should be something in the log and only available devices are shown.

**Comment by daxyorg** [comment]
Hi,

Now all indicators enrols, but with status "unknown".

2024-11-29 18:51:28.837 ERROR (MainThread) [custom_components.grohe_sense.entities.grohe_sense_update_coordinator] Unexpected exception from <bound method DataUpdateCoordinator.async_refresh of <custom_components.grohe_sense.entities.grohe_sense_update_coordinator.GroheSenseUpdateCoordinator object


<img width="369" alt="Screenshot 2024-11-29 at 18 37 04" src="https://github.com/user-attachments/assets/97f148c4-db2e-4fc6-81b6-5bef10aefae0">

**Comment by daxyorg** [comment]
Hi, after some reinstalls of Grohe guard (physicaly)  and the folder grohe_sense, now it's displayed.
I will try to find an error log. 


<img width="388" alt="Screenshot 2024-11-29 at 21 57 58" src="https://github.com/user-attachments/assets/e87d9277-2a10-49b9-878e-aba555e711b4">

**Comment by Flo-Schilli** [comment]
Hi @daxyorg 

I guess it's then really only working with the 03.XX - Firmware - Version unfortunately :disappointed: 

I'll check if I can get some more information about the different firmware versions available and whats the reason for those different versions. So like you mentioned here: [Firmware versions of the devices](https://github.com/Flo-Schilli/homeassistant-grohe_sense/discussions/27#discussioncomment-11402630)

**Comment by daxyorg** [comment]
Thanks a lot for your work and support! I really appreciated!
