### ISSUE TITLE
Missing entities in Grohe sense guard

### ISSUE THREAD

**Issue by LBeeXX** [Flo-Schilli/homeassistant-grohe_sense#56]
Installled Home Assistant - Grohe Sense v0.22.1
No issues during installation, but I only see 1 Device (Sense Guard) and 2 Entities (valve and notifications).

In the output of Action: ‘Grohe Sense: Get Dashboard’  "version" seems to be empty 

Home Assistant version :
Core : 2024.12.5
Supervisor : 2024.12.0
Operating System : 14.1
Frontend : 20241127.8

homeassistant-grohe_sense version :
v0.22.1

Output of  Action: ‘Grohe Sense: Get Dashboard’ 
    rooms:
      - id: xxxxxx (repalced with xxxxxxxx)
        name: Bryggers
        type: 0
        room_type: 4
        role: owner
        appliances:
          - appliance_id: xxxxxx-xxxxxxxx (replaced with xxxxxxx)
            installation_date: "2021-03-11T08:44:35.000+01:00"
            name: MIN GUARD
            serial_number: "no"
            type: 103
            version: ""
            tdt: "2024-12-25T17:52:24.000+01:00"
            timezone: 60
            config:
              thresholds:
                - quantity: flowrate
                  type: min
                  value: 3
                  enabled: false
                - quantity: flowrate
                  type: max
                  value: 50
                  enabled: true
                - quantity: pressure
                  type: min
                  value: 2
                  enabled: false
                - quantity: pressure
                  type: max
                  value: 8
                  enabled: false
                - quantity: temperature_guard
                  type: min
                  value: 5
                  enabled: false
                - quantity: temperature_guard
                  type: max
                  value: 45
                  enabled: false
              measurement_period: 900
              measurement_transmission_intervall: 900
              measurement_transmission_intervall_offset: 1
              action_on_major_leakage: 1
              action_on_minor_leakage: 1
              action_on_micro_leakage: 0
              monitor_frost_alert: true
              monitor_lower_flow_limit: false
              monitor_upper_flow_limit: true
              monitor_lower_pressure_limit: false
              monitor_upper_pressure_limit: false
              monitor_lower_temperature_limit: false
              monitor_upper_temperature_limit: false
              monitor_major_leakage: true
              monitor_minor_leakage: true
              monitor_micro_leakage: true
              monitor_system_error: false
              monitor_btw_0_1_and_0_8_leakage: true
              monitor_withdrawel_amount_limit_breach: true
              detection_interval: 7500
              impulse_ignore: 10
              time_ignore: 20
              pressure_tolerance_band: 10
              pressure_drop: 50
              detection_time: 30
              action_on_btw_0_1_and_0_8_leakage: 1
              action_on_withdrawel_amount_limit_breach: 1
              withdrawel_amount_limit: 200
              sprinkler_mode_start_time: 0
              sprinkler_mode_stop_time: 1439
              sprinkler_mode_active_monday: false
              sprinkler_mode_active_tuesday: false
              sprinkler_mode_active_wednesday: false
              sprinkler_mode_active_thursday: false
              sprinkler_mode_active_friday: false
              sprinkler_mode_active_saturday: false
              sprinkler_mode_active_sunday: false
            role: owner
            registration_complete: true
            calculate_average_since: "2021-03-11T07:44:35.000Z"
            snooze_status: NON_EXISTENT
            data_latest:
              measurement:
                flowrate: 0
                pressure: 6.4
                temperature_guard: 14
                timestamp: "2024-12-25T17:42:57.000+01:00"
              average_monthly_consumption: 9474
              daily_cost: 17.06
              average_daily_consumption: 316
              daily_consumption: 258
              withdrawals:
                starttime: "2024-12-25T17:48:39.000+01:00"
                stoptime: "2024-12-25T17:49:04.000+01:00"
                waterconsumption: 2.3
                maxflowrate: 5.9
            command:
              temp_user_unlock_on: false
              reason_for_change: 1
              pressure_measurement_running: false
              buzzer_on: false
              buzzer_sound_profile: 2
              valve_open: true
              measure_now: false
            notifications: []
            installer:
              name: ""
              email: ""
              phone: ""
            status:
              - type: update_available
                value: 0
              - type: wifi_quality
                value: -1
              - type: connection
                value: 1
    emergency_contacts: []

Output of logfile during configuration : 
2024-12-25 11:08:50.416 DEBUG (MainThread) [custom_components.grohe_sense] Loading Grohe Entry
2024-12-25 11:08:50.603 INFO (MainThread) [custom_components.grohe_sense.api.ondus_api] Login to Ondus API
2024-12-25 11:08:50.604 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Login with username/password
2024-12-25 11:08:51.297 DEBUG (MainThread) [custom_components.grohe_sense.dto.grohe_device] Getting all available Grohe devices
2024-12-25 11:08:51.297 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Get locations
2024-12-25 11:08:51.454 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Get rooms for location xxxxxx
2024-12-25 11:08:51.523 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Get appliances for location xxxxxx and room xxxxxx
2024-12-25 11:08:51.689 DEBUG (MainThread) [custom_components.grohe_sense.dto.grohe_device] Found in location xxxxxx and room xxxxxx the following appliance: xxxxxxx-xxxxxx-xxxxxx-xxxxx from type 103 with name MIN GUARD
2024-12-25 11:08:51.690 DEBUG (MainThread) [custom_components.grohe_sense.sensor] Adding sensor entities from config entry <ConfigEntry entry_id=xxxxxxxxxxxxx version=1 domain=grohe_sense title=Grohe Sense state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=GroheSense>
2024-12-25 11:08:51.690 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Get appliance details for appliance (type insensitive) xxxxx-xxxxxx-xxxxxx
2024-12-25 11:08:51.693 DEBUG (MainThread) [custom_components.grohe_sense.valve] Adding valve entities from config entry <ConfigEntry entry_id=xxxxxxxxxxxxx version=1 domain=grohe_sense title=Grohe Sense state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=GroheSense>
2024-12-25 11:08:51.693 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding valve Valve for device MIN GUARD
2024-12-25 11:08:51.696 DEBUG (MainThread) [custom_components.grohe_sense.todo] Adding todo entities from config entry <ConfigEntry entry_id=xxxxxxxxxxxxx version=1 domain=grohe_sense title=Grohe Sense state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=GroheSense>
2024-12-25 11:08:51.696 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding todo Notifications for device MIN GUARD
2024-12-25 11:08:53.355 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Temperature for device MIN GUARD
2024-12-25 11:08:53.366 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Water consumption for device MIN GUARD
2024-12-25 11:08:53.371 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Average daily consumption for device MIN GUARD
2024-12-25 11:08:53.375 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Latest consumption for device MIN GUARD
2024-12-25 11:08:53.377 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Latest max flow rate for device MIN GUARD
2024-12-25 11:08:53.380 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Average monthly consumption for device MIN GUARD
2024-12-25 11:08:53.382 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Actual flow rate for device MIN GUARD
2024-12-25 11:08:53.385 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Actual pressure for device MIN GUARD
2024-12-25 11:08:53.388 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Latest notification for device MIN GUARD
2024-12-25 11:08:53.391 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up grohe_sense platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/grohe_sense/sensor.py", line 30, in async_setup_entry
    entities.extend(await helper.add_sensor_entities(coordinator, device, notification_config))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/grohe_sense/entities/entity_helper.py", line 55, in add_sensor_entities
    if self._is_valid_version(device, sensor):
       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/config/custom_components/grohe_sense/entities/entity_helper.py", line 27, in _is_valid_version
    return device.stripped_sw_version >= sensor_version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/grohe_sense/dto/grohe_device.py", line 40, in stripped_sw_version
    return tuple(map(int, self.appliance.version.split('.')[:2]))
ValueError: invalid literal for int() with base 10: ''

**Comment by Flo-Schilli** [comment]
Hi @LBeeXX :wave: 

I think I just fixed it with the newest release, can you please try and give me a heads up if it is working for you now.
Thanks also for the Dashboard - Data. It's kinda like strange that there is no version available for your device. Can you please tell me what the Grohe App is telling you about the version of the device. It should be shown at the very bottom after clicking on the Sense Guard behind the 'Current version' field.

Thanks :smile:

**Comment by LBeeXX** [comment]
HI  @Flo-Schilli 
Just ppgraded from v0.22.1 to  v0.22.2 and I can confirm that the issue is fixed - I now see 14 entities 👌
Amazing work 💪💪💪

Regading the Current version, its also blank in the app 

![image](https://github.com/user-attachments/assets/576caf43-b4fe-4061-a105-dc28a085e267)
 
New logfile with no errors 🥳 (just a warning about the missing version) 

2024-12-26 07:17:50.077 DEBUG (MainThread) [custom_components.grohe_sense] Loading Grohe Entry
2024-12-26 07:17:50.327 INFO (MainThread) [custom_components.grohe_sense.api.ondus_api] Login to Ondus API
2024-12-26 07:17:50.328 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Login with username/password
2024-12-26 07:17:51.043 DEBUG (MainThread) [custom_components.grohe_sense.dto.grohe_device] Getting all available Grohe devices
2024-12-26 07:17:51.043 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Get locations
2024-12-26 07:17:51.321 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Get rooms for location xxxxxx
2024-12-26 07:17:51.393 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Get appliances for location xxxxxx and room xxxxxx
2024-12-26 07:17:51.593 DEBUG (MainThread) [custom_components.grohe_sense.dto.grohe_device] Found in location xxxxxx and room xxxxxx the following appliance: xxxxxx from type 103 with name MIN GUARD
2024-12-26 07:17:51.594 DEBUG (MainThread) [custom_components.grohe_sense.sensor] Adding sensor entities from config entry <ConfigEntry entry_id=xxxxxx version=1 domain=grohe_sense title=Grohe Sense state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=GroheSense>
2024-12-26 07:17:51.595 DEBUG (MainThread) [custom_components.grohe_sense.api.ondus_api] Get appliance details for appliance (type insensitive) xxxxxx
2024-12-26 07:17:51.597 DEBUG (MainThread) [custom_components.grohe_sense.valve] Adding valve entities from config entry <ConfigEntry entry_id=xxxxxx version=1 domain=grohe_sense title=Grohe Sense state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=GroheSense>
2024-12-26 07:17:51.597 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding valve Valve for device MIN GUARD
2024-12-26 07:17:51.599 DEBUG (MainThread) [custom_components.grohe_sense.todo] Adding todo entities from config entry <ConfigEntry entry_id=xxxxxx version=1 domain=grohe_sense title=Grohe Sense state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=GroheSense>
2024-12-26 07:17:51.599 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding todo Notifications for device MIN GUARD
2024-12-26 07:17:52.661 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Temperature for device MIN GUARD
2024-12-26 07:17:52.673 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Water consumption for device MIN GUARD
2024-12-26 07:17:52.676 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Average daily consumption for device MIN GUARD
2024-12-26 07:17:52.679 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Latest consumption for device MIN GUARD
2024-12-26 07:17:52.682 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Latest max flow rate for device MIN GUARD
2024-12-26 07:17:52.685 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Average monthly consumption for device MIN GUARD
2024-12-26 07:17:52.687 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Actual flow rate for device MIN GUARD
2024-12-26 07:17:52.690 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Actual pressure for device MIN GUARD
2024-12-26 07:17:52.693 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Latest notification for device MIN GUARD
2024-12-26 07:17:52.695 WARNING (MainThread) [custom_components.grohe_sense.dto.grohe_device] SW-Version for MIN GUARD cannot be split into two numbers. Value is: ""
2024-12-26 07:17:52.695 WARNING (MainThread) [custom_components.grohe_sense.dto.grohe_device] SW-Version for MIN GUARD cannot be split into two numbers. Value is: ""
2024-12-26 07:17:52.695 WARNING (MainThread) [custom_components.grohe_sense.dto.grohe_device] SW-Version for MIN GUARD cannot be split into two numbers. Value is: ""
2024-12-26 07:17:52.696 WARNING (MainThread) [custom_components.grohe_sense.dto.grohe_device] SW-Version for MIN GUARD cannot be split into two numbers. Value is: ""
2024-12-26 07:17:52.696 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Update available for device MIN GUARD
2024-12-26 07:17:52.698 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Wifi quality for device MIN GUARD
2024-12-26 07:17:52.701 DEBUG (MainThread) [custom_components.grohe_sense.entities.entity_helper] Adding sensor Online for device MIN GUARD

**Comment by Flo-Schilli** [comment]
Its really great that it is working now 👍
Let's see if one day there will be a version for you from Grohe 😂

I'm gonna close the issue now 😊
